### ISSUE TITLE
Will he sing 🎤 ?

### ISSUE THREAD

**Issue by pyrbin** [smultronbusken/alexander-bard-for-discord#1]
I'm rly looking forward to this!! Such an amazing and awesome and astounding (tripple A) concept. 

One concern/question tho, will he sing? Like in the band?

You should do that.

**Comment by smultronbusken** [comment]
He will sing yes of course, he is Alexander Bard after all. It will also feature a quest where you apply to the Bard's College (skyrim reference for stupid people).

**Comment by smultronbusken** [comment]
Alexander Bard now sings.

**Comment by pyrbin** [comment]
ok my face went from 😄 to ----> (arrow right) to this --> this 😁and then ultimately this --> (this) 🤣(more emojis for showing insense of happy -- >🤣🤣🤣). This will truly revolutionalize the discord bot (and overall alexander bard content) communitites. Thanks you SIR and Good Night!

**Comment by smultronbusken** [comment]
😑
